import Head from 'next/head';
import { useState } from 'react';

import Data from '../components/data';

export default function Home() {
  const [toggle, setToggle] = useState(null);

  return (
    <div>
      <Head>
        <title>Sistem G-PASS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        Menu Utama
        <div className='grid grid-cols-2'>
          <div>
            <button
              className='capitalize bg-green-400 rounded-md shadow-xl p-2 hover:bg-admin1 transition-all'
              onClick={() => setToggle('pegawai')}
            >
              PEGAWAI PERGIGIAN
            </button>
          </div>
          <div>
            <button
              className='capitalize bg-green-400 rounded-md shadow-xl p-2 hover:bg-admin1 transition-all'
              onClick={() => setToggle('juruterapi')}
            >
              JURUTERAPI PERGIGIAN
            </button>
          </div>
        </div>
        {toggle ? <Data toggle={toggle} /> : null}
      </div>
    </div>
  );
}
